- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print Fruit Names
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - banana
        - grapes
        - orange
    - name: Print Fruit Name with Quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.Name }}, Quantity - {{ item.Quantity }}
      loop:
        - { Name: apple, Quantity: 100 }
        - { Name: banana, Quantity: 200 }
        - { Name: grapes, Quantity: 300 }
        - { Name: orange, Quantity: 500 }